#ifndef DATAINTEROP_GLOBAL_H
#define DATAINTEROP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAINTEROP_LIBRARY)
#  define DATAINTEROPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAINTEROPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAINTEROP_GLOBAL_H
